name: Bug Report
description: Fill a bug report
title: "Issue title"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking some time to fill out this bug report! 🙏🏼
  - type: checkboxes
    attributes:
      description: Check first if the issue is live on the latest version of the starter. If you are unsure, please check it out on the [community page](https://go.bearstudio.fr/start-ui-figma).
      options:
        - label: Can you reproduce this bug on the latest version of the starter?
          required: false     
  - type: dropdown
    id: version
    attributes:
      label: Type of element concerned
      description: Where did you experienced your problem?
      options:
        - 🎓  Tutorials
        - 💻  Web app Desktop [web]
        - 📱  Mobile App [native]
        - ⭐️  Icons
        - 💊  Components
        - 💎  Brand
        - 🎨  Styles
        - 🌈  Colors library
        - ➕  Other...
    validations:
      required: false      
  - type: textarea
    id: which-feature
    attributes:
      label: What is your feature??
      description: Explain us the feature/subject. Drop some screenshots, videos or files to make it clearer. Have you added it on your own file? Do not hesitate to share your feature making a copy of your .fig so we can add it on a future version.
      placeholder: What can you see?
    validations:
      required: true
