name: Bug Report
description: Fill a bug report
title: "Issue title"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking some time to fill out this bug report! 🙏🏼
  - type: checkboxes
    attributes:
      description: Check first if the issue is live on the latest version of the starter. If you are unsure, please check it out on the [community page](https://go.bearstudio.fr/start-ui-figma).
      options:
        - label: Can you reproduce this bug on the latest version of the starter?
          required: false     
  - type: dropdown
    id: version
    attributes:
      label: Type of elements concerned
      description: Where did you experienced your problem?
      options:
        - 🎓 Tutorials
        - 💻 Web app Desktop [web]
        - 📱 Mobile App [native]
        - ⭐️ Icons
        - 💊 Components
        - 💎 Brand
        - 🎨 Styles
        - 🌈 Colors library
        - ➕ Other...
    validations:
      required: false      
  - type: textarea
    id: what-happened
    attributes:
      label: What is the problem you are encountering? 
      description: Explain to us what the problem is. Drop some screenshots, vidéos or files to make it clearer.
      placeholder: What can you see?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What do you suggest to improve  
      description: Have you thought about the solution? Do you have any idea how to fix the issue? Have you fixed it on your own file? Do not hesitate fix it yourself and then make a copy of your .fig.
    validations:
      required: false
