name: Feature request
description: Submit a new feature request
title: "Subject title"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking some time to fill out this feature request form! 🙏🏼
  - type: checkboxes
    attributes:
      description: Check first if the feature is not already live the latest version of the starter. If you are unsure, please check it out on the [community page](https://go.bearstudio.fr/start-ui-figma).
      options:
        - label: Is this feature is not on the latest version of the starter?
          required: false     
  - type: dropdown
    id: version
    attributes:
      label: Type of element concerned
      description: What part would benefit this new feature?
      options:
        - 🎓  Tutorials
        - 💻  Web app Desktop [web]
        - 📱  Mobile App [native]
        - ⭐️  Icons
        - 💊  Components
        - 💎  Brand
        - 🎨  Styles
        - 🌈  Colors library
        - ➕  Other...
    validations:
      required: false      
  - type: textarea
    id: which-feature
    attributes:
      label: What is your feature?
      description: Explain us the feature/subject. Drop some screenshots, videos or files to make it clearer. Have you added it on your own file? Do not hesitate to share your feature making a copy of your .fig so we can add it on a future version.
      placeholder: What can you see?
    validations:
      required: true
